### ISSUE TITLE
son-validate: package signing validation

### ISSUE THREAD

**Issue by lconceicao** [sonata-nfv/son-cli#205]
son-validate must verify if a package is correctly signed.
@dang03 We discussed this in the last F2F, what are the required parameters for this?

**Comment by dang03** [comment]
@lconceicao 
In order to verify a signature, the next parameters are required:
- `signature`
- `package file` OR package file's `hash`
- owner's `public key`
A signature is a `string` that looks like:
`SIGNATURE =  9561913047565233690517755226241283855285...`

The `verify` method could be something like:
The `package file` or the package file's `hash` is sent along with the `signature` and  the owner's `public key`, in order to verify the package.
Then, `son-validate` calculates the hash value of the package file (if package file was sent) and then uses the public key `verify()` method to validate its origin.

```
def verify(public_key, signature, package_file):
    from Crypto.Hash import SHA256
    from Crypto.PublicKey import RSA
    hash = SHA256.new(package_file).digest()
    result = public_key.verify(hash, signature)
    if result:
      print("OK")
    else:
      print("FAILED")
```

**Comment by lconceicao** [comment]
done.
